print 'Hello World'
a = input()
print "input:", a
print "input:", a
print "input:", a
print "input:", a
print "input:", a
print "input:", a
print "input:", a
print "input:", a
print "input:", a
print "input:", a
print "input:", a
print "input:", a
print "input:", a
print "input:", a
print "input:", a
print "input:", a
print "input:", a
print "input:", a
print "input:", a
print "input:", a
print "input:", a
print "input:", a
print "input:", a
print "input:", a
print "input:", a
print "input:", a
print "input:", a
print "input:", a
print "input:", a
print "input:", a
print "input:", a
  